vnc:
    #build: .
    image: jonathangerlach/dwarffortress_vnc:44.12
    ports:
        - "5901:5901"
    volumes:
        - $HOME/DwarfFortressSaves:/opt/dwarfFortress/data/save
x11:
    #build: .
    image: jonathangerlach/dwarffortress_x11:44.12
    environment:
        DISPLAY: $DISPLAY
    volumes:
        - $HOME/DwarfFortressSaves:/opt/dwarfFortress/data/save
        - /tmp/.X11-unix:/tmp/.X11-unix
        - $HOME/.Xauthority:/home/dorf/.Xauthority